# Generated by Django 2.2.5 on 2019-10-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magnifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
